"""Build the public CV (cv/cv-public.tex) with publications from data/publications.json.

Run: python3 scripts/build_cv.py
Regenerates cv/publications-conference-a.tex, cv/publications-conference-b.tex,
cv/publications-journal.tex, and cv/publications-counts.tex from the website's
publication records, compiles the CV with Tectonic (or latexmk/xelatex), and
copies it to assets/Kshitij_Mishra_CV.pdf. Edit the other cv/*.tex files directly.
"""
from datetime import datetime, timezone
from pathlib import Path
import os
import shutil
import subprocess
import sys
import tempfile

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'scripts'))
from build_publications import load_records, venue_family, venue_group  # noqa: E402

CV = ROOT / 'cv'
PDF = ROOT / 'assets/Kshitij_Mishra_CV.pdf'
# Conference entries on the first Conference Publications page (page 2); the rest
# follow under "Conference Publications (continued)". Lower it if page 2 overflows.
CONFERENCE_FIRST_PAGE = 12
SPECIAL = {'&': r'\&', '%': r'\%', '$': r'\$', '#': r'\#', '_': r'\_', '{': r'\{', '}': r'\}',
           '~': r'\textasciitilde{}', '^': r'\textasciicircum{}', '\\': r'\textbackslash{}',
           '²': r'\textsuperscript{2}', '–': '--', '—': '---'}

def tex(text):
    return ''.join(SPECIAL.get(char, char) for char in text)

def link(url):
    return url.replace('%', r'\%').replace('#', r'\#')

def author(entry):
    name = tex(entry['name'])
    if entry['name'] == 'Kshitij Mishra':
        name = r'\textbf{' + name + '}'
    if entry.get('first') or entry.get('coFirst'):
        name = r'\firstauthor{' + name + '}'
    return name

def render(pub):
    """One \\publication{label}{title}{authors}{venue}{links} line (macro in cv/settings.sty)."""
    short = pub.get('cvLabel') or (venue_group(pub) if pub['kind'] == 'journal' else venue_family(pub))
    label = tex(short) + " '" + str(pub['year'])[-2:]
    if venue_group(pub).startswith('Findings of '):
        label += r'\newline Findings'
    title = tex(pub['title'])
    if pub.get('url'):
        title = r'\href{' + link(pub['url']) + '}{' + title + '}'
    authors = ', '.join(author(a) for a in pub['authors']) + '.'
    venue = tex(pub['venue'])
    if pub['kind'] == 'journal':
        venue += f" ({pub['year']})"
    if pub.get('metadata'):
        venue += ', ' + tex(pub['metadata'])
    if pub['status'] == 'accepted':
        venue += r'. \textbf{Accepted}'
    links = [r'\resource{' + link(pub[key]) + '}{' + text + '}' for key, text in (('url', 'Paper'), ('code', 'Code')) if pub.get(key)]
    return r'\publication{' + label + '}{' + title + '}{' + authors + '}{' + venue + '.}{' + r'\enspace '.join(links) + '}\n'

def write_publications(records):
    conference = [p for p in records if p['kind'] == 'conference']
    journals = [p for p in records if p['kind'] == 'journal']
    skipped = [p['id'] for p in records if p['kind'] not in ('conference', 'journal')]
    if skipped:
        print('Not in the CV (only conference and journal lists exist): ' + ', '.join(skipped))
    note = '% Generated by scripts/build_cv.py from data/publications.json; edit that file instead.\n'
    parts = {'publications-conference-a.tex': conference[:CONFERENCE_FIRST_PAGE],
             'publications-conference-b.tex': conference[CONFERENCE_FIRST_PAGE:],
             'publications-journal.tex': journals}
    for name, items in parts.items():
        (CV / name).write_text(note + ''.join(render(p) for p in items), encoding='utf-8')
    (CV / 'publications-counts.tex').write_text(
        note + f'\\newcommand{{\\ConferenceCount}}{{{len(conference)}}}\n\\newcommand{{\\JournalCount}}{{{len(journals)}}}\n',
        encoding='utf-8')
    return len(conference), len(journals)

def compile_cv():
    env = dict(os.environ)
    # Builds on the same day are byte-identical, so a local build and the GitHub build agree.
    today = datetime.now(timezone.utc).replace(hour=0, minute=0, second=0, microsecond=0)
    env.setdefault('SOURCE_DATE_EPOCH', str(int(today.timestamp())))
    local = Path.home() / '.local/bin/tectonic'
    tectonic = shutil.which('tectonic') or (str(local) if local.exists() else None)
    with tempfile.TemporaryDirectory() as out:
        if tectonic:
            command = [tectonic, '-X', 'compile', '--outdir', out, 'cv-public.tex']
        elif shutil.which('latexmk'):
            command = ['latexmk', '-xelatex', '-interaction=nonstopmode', '-halt-on-error', f'-outdir={out}', 'cv-public.tex']
        else:
            raise SystemExit('Install Tectonic (https://tectonic-typesetting.github.io) or TeX Live with latexmk and XeLaTeX.')
        result = subprocess.run(command, cwd=CV, env=env, capture_output=True, text=True)
        if result.returncode:
            raise SystemExit(f'CV compilation failed:\n{result.stdout[-3000:]}\n{result.stderr[-3000:]}')
        shutil.copyfile(Path(out) / 'cv-public.pdf', PDF)

if __name__ == '__main__':
    conference, journals = write_publications(load_records())
    compile_cv()
    print(f'Built {PDF.relative_to(ROOT)}: {conference} conference papers, {journals} journal articles.')
